import { useEffect, useState } from 'react';
import { api } from '../lib/api';

export default function AdminReviewEditor({movie,onSaved}){
 const [open,setOpen]=useState(false),[name,setName]=useState('Scapegoat'),[text,setText]=useState(''),[status,setStatus]=useState(''),[exists,setExists]=useState(false);
 useEffect(()=>{setOpen(false);setStatus('');api(`/api/admin/reviews/movie/${movie.id}`).then(d=>{if(d.review){setText(d.review.review_text||'');setName(d.review.admin_name||'Scapegoat');setExists(true)}else{setText('');setName('Scapegoat');setExists(false)}}).catch(()=>{})},[movie.id]);
 const save=async e=>{e.preventDefault();if(!text.trim())return;setStatus('Publishing…');try{await api('/api/admin/reviews/save',{method:'POST',body:JSON.stringify({movieId:movie.id,movieTitle:movie.title,adminName:name,reviewText:text})});setExists(true);setStatus('✓ Review live ho gaya');onSaved?.()}catch(e){setStatus('✕ '+e.message)}};
 return <section className={`inline-review-editor ${open?'open':''}`}><button className="editor-toggle" onClick={()=>setOpen(!open)}><span>✎</span><div><small>ADMIN REVIEW MODE</small><b>{exists?'Edit official review':'Write official review'}</b></div><em>{open?'−':'＋'}</em></button>{open&&<form onSubmit={save}><div className="made-by"><label>REVIEW MADE BY</label><input value={name} maxLength="50" onChange={e=>setName(e.target.value)} placeholder="Scapegoat"/></div><div className="review-for"><small>REVIEWING</small><b>{movie.title}</b><span>TMDB #{movie.id}</span></div><div className="review-write-head"><label>YOUR FULL REVIEW</label><span>{text.length}/12,000</span></div><textarea maxLength="12000" value={text} onChange={e=>setText(e.target.value)} placeholder={'🎬 '+movie.title.toUpperCase()+' - Review\n\nApna detailed honest review yahan likho...\n\nMy Rating ✨: 9/10 ⭐ (Highly Recommended 🔥)\n\n📺 Platform: Prime Video\n\n⚠️ Parental Guidance: 18+ recommended.'}/><div className="auto-format-note"><i>✦</i><span><b>Smart formatting enabled</b>Rating, platform, guidance aur overall score automatically alag premium cards mein show honge.</span></div><div className="editor-publish"><span className={status.startsWith('✓')?'ok':''}>{status}</span><button disabled={!text.trim()}>{exists?'Update review':'Publish review'} →</button></div></form>}</section>
}
