import { useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';

const icons={visitors:'◉',views:'↗',users:'♙',reviews:'✦',comments:'◌',likes:'♥'};
export default function AdminDashboard({onClose}){
 const [authed,setAuthed]=useState(false),[password,setPassword]=useState(''),[error,setError]=useState(''),[data,setData]=useState(null),[days,setDays]=useState(7),[loading,setLoading]=useState(true);
 const [editorOpen,setEditorOpen]=useState(false),[editor,setEditor]=useState({movieId:'',movieTitle:'',adminName:'Scapegoat',reviewText:''}),[saveState,setSaveState]=useState('');
 const check=()=>api('/api/admin/session').then(d=>{setAuthed(d.authenticated);setLoading(false);if(d.authenticated)load(days)});
 const load=d=>{setLoading(true);api(`/api/admin/analytics?days=${d}`).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{check()},[]);useEffect(()=>{if(authed)load(days)},[days]);
 const login=async e=>{e.preventDefault();setError('');try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password})});setPassword('');setAuthed(true);load(days)}catch(e){setError(e.message)}};
 const logout=async()=>{await api('/api/admin/logout',{method:'POST'});setAuthed(false);setData(null)};
 const saveReview=async e=>{e.preventDefault();setSaveState('Saving…');try{await api('/api/admin/reviews/save',{method:'POST',body:JSON.stringify(editor)});setSaveState('✓ Review published with structured details');load(days)}catch(e){setSaveState(e.message)}};
 const max=useMemo(()=>Math.max(1,...(data?.daily||[]).map(x=>x.visitors)),[data]);
 return <div className="admin-shell"><aside><div className="admin-logo">C<span>·</span>M</div><nav><button className="active">▦<span>Overview</span></button><button>⌁<span>Audience</span></button><button>✦<span>Reviews</span></button><button>◌<span>Comments</span></button></nav><button className="admin-exit" onClick={onClose}>←<span>Website</span></button></aside><main className="admin-main">
  <header><div><small>CINE·MOOD CONTROL ROOM</small><h1>Analytics overview</h1><p>Traffic, community aur content performance ek jagah.</p></div><div className="admin-head-actions">{authed&&<select value={days} onChange={e=>setDays(+e.target.value)}><option value="7">Last 7 days</option><option value="14">Last 14 days</option><option value="30">Last 30 days</option></select>}<button onClick={onClose}>×</button></div></header>
  {loading&&!authed?<div className="dash-loading">Loading secure dashboard…</div>:!authed?<section className="admin-login-card"><div className="admin-lock">⌾</div><small>RESTRICTED ANALYTICS</small><h2>Welcome back, Scapegoat</h2><p>Dashboard access ke liye admin password enter karo.</p><form onSubmit={login}><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Admin password"/><button>Unlock dashboard →</button></form>{error&&<b className="admin-error">{error}</b>}</section>:<>
   <div className="dash-toolbar"><span><i/> Live database</span><button className="new-review-btn" onClick={()=>setEditorOpen(!editorOpen)}>＋ New expert review</button><button onClick={()=>load(days)}>↻ Refresh</button><button onClick={logout}>Sign out</button></div>
   {editorOpen&&<section className="review-editor"><header><div><small>SCAPEGOAT EDITORIAL</small><h2>Publish expert review</h2></div><button onClick={()=>setEditorOpen(false)}>×</button></header><form onSubmit={saveReview}><div className="editor-fields"><label>TMDB MOVIE ID<input value={editor.movieId} onChange={e=>setEditor({...editor,movieId:e.target.value})} placeholder="e.g. 108978"/></label><label>MOVIE / SHOW TITLE<input value={editor.movieTitle} onChange={e=>setEditor({...editor,movieTitle:e.target.value})} placeholder="Reacher Season 4 (2026)"/></label><label>ADMIN NAME<input value={editor.adminName} onChange={e=>setEditor({...editor,adminName:e.target.value})}/></label></div><label>FULL REVIEW<textarea value={editor.reviewText} onChange={e=>setEditor({...editor,reviewText:e.target.value})} placeholder={'🎬 TITLE - Review\n\nWrite paragraphs...\n\nMy Rating ✨: 9/10 ⭐\n\n📺 Platform: Prime Video\n\n⚠️ Parental Guidance: 18+ recommended.'}/></label><div className="editor-foot"><span>{editor.reviewText.length}/12,000 · Rating, Platform aur Guidance automatically separate honge.</span><button disabled={!editor.movieId||!editor.movieTitle||!editor.reviewText}>Publish review →</button></div>{saveState&&<b className="save-state">{saveState}</b>}</form></section>}
   {loading&&!data?<div className="dash-loading">Crunching the numbers…</div>:data&&<><section className="metric-grid">{Object.entries(data.summary).filter(([k])=>k!=='adminReviews').map(([k,v])=><article key={k}><span>{icons[k]||'◇'}</span><small>{k}</small><strong>{Number(v).toLocaleString('en-IN')}</strong><em>{k==='visitors'?'Unique audience':k==='users'?'Google accounts':`Last ${days} days`}</em></article>)}</section>
   <section className="dash-grid"><article className="chart-card"><header><div><small>AUDIENCE TREND</small><h2>Unique visitors</h2></div><b>{data.summary.visitors}</b></header><div className="bar-chart">{data.daily.map(d=><div className="bar-col" key={d.date}><span className="bar-tip">{d.visitors}</span><i style={{height:`${Math.max(3,d.visitors/max*100)}%`}}/><small>{d.label}</small></div>)}</div></article>
   <article className="health-card"><small>COMMUNITY HEALTH</small><h2>Engagement mix</h2>{[['Reviews',data.summary.reviews,'#e50914'],['Comments',data.summary.comments,'#8b5cf6'],['Likes',data.summary.likes,'#e6bd65']].map(([n,v,c])=><div className="progress" key={n}><span>{n}<b>{v}</b></span><i><em style={{width:`${Math.min(100,(v/Math.max(1,data.summary.reviews+data.summary.comments+data.summary.likes))*100)}%`,background:c}}/></i></div>)}<div className="health-foot"><strong>{data.summary.adminReviews}</strong><span>Published expert verdicts</span></div></article></section>
   <section className="dash-grid lower"><article className="table-card"><header><div><small>CONTENT PERFORMANCE</small><h2>Top expert reviews</h2></div></header>{data.topMovies.length?data.topMovies.map((m,i)=><div className="top-row" key={m.id}><b>{String(i+1).padStart(2,'0')}</b><span>{m.title}</span><em>♥ {m.likes}</em><em>◌ {m.comments}</em></div>):<p className="dash-empty">Engagement aate hi ranking yahan dikhegi.</p>}</article><article className="activity-card"><header><small>LATEST ACTIVITY</small><h2>Community pulse</h2></header>{data.recent.length?data.recent.map((x,i)=><div className="activity" key={i}><i>{x.type==='review'?'✦':'◌'}</i><div><b>{x.title}</b><p>{x.text}</p><small>{x.movie} · {new Date(x.at).toLocaleString('en-IN')}</small></div></div>):<p className="dash-empty">Abhi koi recent activity nahi.</p>}</article></section></>}
  </>}
 </main></div>
}
