import { useEffect, useMemo, useState } from 'react';
import { api, imageUrl, initAuth, signInGoogle, signOut } from './lib/api';
import AdminReview from './components/AdminReview';
import AdminReviewEditor from './components/AdminReviewEditor';
import UserReviews from './components/UserReviews';
import AdminDashboard from './components/AdminDashboard';
import SupportModal from './components/SupportModal';
import MenuDrawer from './components/MenuDrawer';

const genres = [['Trending',''],['Action','28'],['Sci-Fi','878'],['Thriller','53'],['Comedy','35'],['Horror','27'],['Romance','10749'],['Animation','16']];
function MovieCard({m,onOpen,rank}) { return <button className="movie-card" onClick={()=>onOpen(m)}>{rank&&<span className="rank">{rank}</span>}<img src={imageUrl(m.poster_path,'w342')} alt="" loading="lazy"/><span className="card-shade"/><span className="play">▶</span><div><b>{m.title}</b><small><i>{Math.round((m.vote_average||0)*10)}% Match</i> · {m.release_date?.slice(0,4)||'TBA'}</small></div></button> }
function Rail({title,movies,onOpen,ranked=false}) { return <section className="rail"><header><h2>{title}</h2><button>Explore all ›</button></header><div className="rail-track">{movies.map((m,i)=><MovieCard key={`${m.id}-${i}`} m={m} onOpen={onOpen} rank={ranked&&i<10?i+1:null}/>)}</div></section> }

export default function App(){
 const [movies,setMovies]=useState([]),[moviesLoading,setMoviesLoading]=useState(true),[appError,setAppError]=useState(''),[active,setActive]=useState(''),[selected,setSelected]=useState(null),[review,setReview]=useState(null),[reviewVersion,setReviewVersion]=useState(0),[trailer,setTrailer]=useState(null),[trailerOpen,setTrailerOpen]=useState(false),[search,setSearch]=useState(''),[profile,setProfile]=useState(null),[menu,setMenu]=useState(false),[adminOpen,setAdminOpen]=useState(false),[adminAuthed,setAdminAuthed]=useState(false),[supportOpen,setSupportOpen]=useState(false),[welcomeDonate,setWelcomeDonate]=useState(false),[drawerOpen,setDrawerOpen]=useState(false);
 const load=async(g='')=>{setMoviesLoading(true);setAppError('');try{const p=g?`discover/movie?with_genres=${g}&sort_by=popularity.desc`:'trending/movie/day';const d=await api(`/api/movies/${p}`);if(!d.results?.length)throw new Error('No movies returned');setMovies(d.results)}catch(e){setAppError('Movie service connect nahi hua. API environment aur deployment check karo.')}finally{setMoviesLoading(false)}};
 const openMovie=m=>setSelected(m);
 const googleLogin=()=>signInGoogle();
 const openSupport=()=>{setWelcomeDonate(false);setSupportOpen(true)};
 useEffect(()=>{load();api('/api/admin/session').then(d=>setAdminAuthed(d.authenticated)).catch(()=>{});initAuth().then(async c=>{if(!c)return;const {data:{session}}=await c.auth.getSession();setProfile(session?.user||null);c.auth.onAuthStateChange((_,s)=>setProfile(s?.user||null))}).catch(()=>{});const seen=sessionStorage.getItem('cine_welcome_seen');if(!seen){sessionStorage.setItem('cine_welcome_seen','1');const t=setTimeout(()=>{setWelcomeDonate(true);setSupportOpen(true)},900);return()=>clearTimeout(t)}},[]);
 useEffect(()=>{if(selected){setReview(null);setTrailer(null);setTrailerOpen(false);api(`/api/review/${selected.id}`).then(setReview);api(`/api/movies/movie/${selected.id}/videos`).then(d=>{const videos=(d.results||[]).filter(v=>v.site==='YouTube');setTrailer(videos.find(v=>v.type==='Trailer'&&v.official)||videos.find(v=>v.type==='Trailer')||videos.find(v=>v.type==='Teaser')||null)}).catch(()=>setTrailer(null))}},[selected]);
 const hero=movies[0]; const filtered=useMemo(()=>search?movies.filter(m=>m.title?.toLowerCase().includes(search.toLowerCase())):movies,[movies,search]);
 const choose=g=>{setActive(g);setSearch('');load(g)};
 return <div>
  <nav className="topbar"><a className="brand" href="#top">CINE<span>·</span>MOOD <em>AI</em></a><div className="desktop-links"><a href="#discover">Discover</a><a href="#community">Community</a><button onClick={()=>setAdminOpen(true)}>{adminAuthed?'Review mode ✓':'Admin reviews'}</button><button className="support-link" onClick={openSupport}>♥ Support</button></div><div className="nav-actions"><button className="menu-trigger" onClick={()=>setDrawerOpen(true)} aria-label="Open menu">☰</button><label className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search movies"/></label><button className="profile" onClick={()=>setMenu(!menu)}>{profile?.user_metadata?.avatar_url?<img src={profile.user_metadata.avatar_url}/>:<span>G</span>}<b>{profile?'Account':'Login'}</b></button></div>{menu&&<div className="account-pop"><b>{profile?.user_metadata?.full_name||'Guest viewer'}</b><small>{profile?'Google account · Activity saved':'Browse freely. Login to review, like or comment.'}</small>{profile?<button onClick={()=>signOut()}>Sign out</button>:<button onClick={googleLogin}>Continue with Google</button>}</div>}</nav>
  {moviesLoading&&!hero&&<div className="app-state"><div className="spinner"/><h2>Loading CineMood</h2><p>Fresh movies ready ho rahi hain…</p></div>}
  {appError&&!hero&&<div className="app-state error-state"><span>!</span><h2>Connection issue</h2><p>{appError}</p><button onClick={()=>load(active)}>Try again</button></div>}
  {hero&&<header id="top" className="hero" style={{'--hero':`url("${imageUrl(hero.backdrop_path,'w1280')}")`}}><div className="hero-content"><span className="eyebrow">#1 IN MOVIES TODAY</span><h1>{hero.title}</h1><div className="hero-meta"><i>{Math.round(hero.vote_average*10)}% Match</i><span>{hero.release_date?.slice(0,4)}</span><span>U/A 16+</span><span>4K</span></div><p>{hero.overview}</p><div><button className="primary" onClick={()=>openMovie(hero)}>▶ View details</button><button className="secondary" onClick={()=>openMovie(movies[Math.floor(Math.random()*movies.length)])}>✦ Surprise me</button></div></div></header>}
  <main id="discover"><div className="genre-bar">{genres.map(([n,g])=><button className={active===g?'on':''} onClick={()=>choose(g)} key={n}>{n}</button>)}</div><Rail title={search?`Results for “${search}”`:'Top 10 today'} movies={filtered.slice(0,10)} onOpen={openMovie} ranked={!search}/><Rail title="Popular right now" movies={[...filtered].reverse()} onOpen={openMovie}/><Rail title="Made for your mood" movies={filtered.slice(4).concat(filtered.slice(0,4))} onOpen={openMovie}/></main>
  <footer>Made in India · Powered by TMDB, Gemini & the community</footer>
  {selected&&<div className="modal-wrap" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><article className="detail"><button className="close" onClick={()=>setSelected(null)}>×</button><div className="detail-visual" style={{'--backdrop':`url("${imageUrl(selected.backdrop_path,'w1280')}")`}}><div><h2>{selected.title}</h2><span>{selected.release_date?.slice(0,4)} · ⭐ {selected.vote_average?.toFixed(1)}</span><div className="detail-actions"><button className="watch-trailer" onClick={()=>trailer?setTrailerOpen(true):window.open(`https://www.youtube.com/results?search_query=${encodeURIComponent(selected.title+' official trailer')}`,'_blank')}>▶ {trailer?'Watch official trailer':'Find trailer on YouTube'} <i>HD</i></button></div></div></div>{trailerOpen&&trailer&&<div className="trailer-player"><header><div><i/> NOW PLAYING <b>{trailer.name}</b></div><button onClick={()=>setTrailerOpen(false)}>×</button></header><div><iframe src={`https://www.youtube-nocookie.com/embed/${trailer.key}?autoplay=1&rel=0&modestbranding=1`} title={`${selected.title} official trailer`} allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen/></div></div>}<div className="detail-body"><div className="overview"><span className="match">{Math.round(selected.vote_average*10)}% Match</span><p>{selected.overview}</p></div>{adminAuthed&&<AdminReviewEditor movie={selected} onSaved={()=>setReviewVersion(v=>v+1)}/>}<AdminReview key={`${selected.id}-${reviewVersion}`} movieId={selected.id} fallback={review} isLoggedIn={!!profile} onLogin={googleLogin}/><UserReviews movie={selected} isLoggedIn={!!profile} onLogin={googleLogin}/></div></article></div>}
  {adminOpen&&<AdminDashboard onClose={()=>setAdminOpen(false)} onAuthChange={setAdminAuthed}/>} 
  {drawerOpen&&<MenuDrawer onClose={()=>setDrawerOpen(false)} onSupport={openSupport} onAdmin={()=>setAdminOpen(true)}/>}
  {supportOpen&&<SupportModal welcome={welcomeDonate} onClose={()=>{setSupportOpen(false);setWelcomeDonate(false)}}/>}
  <nav className="mobile-nav"><button className="on">⌂<span>Home</span></button><button>⌕<span>Search</span></button><button onClick={()=>setMenu(!menu)}>◎<span>Profile</span></button><button onClick={()=>setAdminOpen(true)}>▦<span>Admin</span></button><button className="support-mobile" onClick={openSupport}>♥<span>Support</span></button></nav>
 </div>
}
