-- CINE·MOOD community + hybrid guest/Google auth
-- Safe to run repeatedly in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Guest',
  avatar_url text,
  is_guest boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_reviews (
  id bigint generated by default as identity primary key,
  movie_id text not null unique,
  movie_title text not null default '',
  admin_name text not null default 'Scapegoat',
  review_text text not null,
  rating numeric(3,1) check (rating between 0 and 10),
  verdict text check (verdict in ('MUST WATCH','WORTH WATCHING','ONE-TIME WATCH','SKIP IT')),
  platform text,
  parental_guidance text,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_review_likes (
  admin_review_id bigint not null references public.admin_reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (admin_review_id, user_id)
);

create table if not exists public.admin_review_comments (
  id bigint generated by default as identity primary key,
  admin_review_id bigint not null references public.admin_reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  parent_comment_id bigint references public.admin_review_comments(id) on delete cascade,
  comment_text text not null check (char_length(comment_text) between 1 and 500),
  is_pinned boolean not null default false,
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comment_likes (
  comment_id bigint not null references public.admin_review_comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, user_id)
);

-- Existing user reviews stay readable; new reviews are tied to a verified Google user.
alter table if exists public.user_reviews add column if not exists user_id uuid references auth.users(id) on delete set null;
create table if not exists public.user_review_likes (
  review_id bigint not null references public.user_reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (review_id, user_id)
);
create index if not exists idx_user_review_likes_review on public.user_review_likes(review_id);

-- Preserve existing custom admin reviews from the previous app when that table exists.
do $$
begin
  if to_regclass('public.custom_reviews') is not null then
    insert into public.admin_reviews (movie_id, movie_title, admin_name, review_text, updated_at)
    select movie_id::text, coalesce(movie_title, ''),
           case when lower(coalesce(admin_name, '')) like '%scapegoat%' then 'Scapegoat' else coalesce(admin_name, 'Scapegoat') end,
           admin_review, coalesce(updated_at, now())
    from public.custom_reviews
    where admin_review is not null
    on conflict (movie_id) do nothing;
  end if;
end $$;

create index if not exists idx_admin_comments_review on public.admin_review_comments(admin_review_id, created_at desc);
create index if not exists idx_admin_review_likes_review on public.admin_review_likes(admin_review_id);
create index if not exists idx_comment_likes_comment on public.comment_likes(comment_id);

-- Automatically create/update the public profile for anonymous and Google users.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name, avatar_url, is_guest)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', 'Guest ' || upper(right(replace(new.id::text, '-', ''), 4))),
    new.raw_user_meta_data->>'avatar_url',
    coalesce(new.is_anonymous, false)
  )
  on conflict (id) do update set
    display_name = excluded.display_name,
    avatar_url = excluded.avatar_url,
    is_guest = excluded.is_guest,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of raw_user_meta_data on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.admin_reviews enable row level security;
alter table public.admin_review_likes enable row level security;
alter table public.admin_review_comments enable row level security;
alter table public.comment_likes enable row level security;
alter table public.user_review_likes enable row level security;

-- Public content is readable. Mutations go through the Express server with verified JWT.
drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles for select using (true);
drop policy if exists "published admin reviews readable" on public.admin_reviews;
create policy "published admin reviews readable" on public.admin_reviews for select using (published = true);
drop policy if exists "admin review likes readable" on public.admin_review_likes;
create policy "admin review likes readable" on public.admin_review_likes for select using (true);
drop policy if exists "visible comments readable" on public.admin_review_comments;
create policy "visible comments readable" on public.admin_review_comments for select using (is_hidden = false);
drop policy if exists "comment likes readable" on public.comment_likes;
create policy "comment likes readable" on public.comment_likes for select using (true);
drop policy if exists "user review likes readable" on public.user_review_likes;
create policy "user review likes readable" on public.user_review_likes for select using (true);

-- Revoke anonymous direct mutation: server/service-role remains in control.
revoke insert, update, delete on public.admin_reviews from anon, authenticated;
revoke insert, update, delete on public.admin_review_likes from anon, authenticated;
revoke insert, update, delete on public.admin_review_comments from anon, authenticated;
revoke insert, update, delete on public.comment_likes from anon, authenticated;
revoke insert, update, delete on public.user_review_likes from anon, authenticated;

grant select on public.profiles, public.admin_reviews, public.admin_review_likes, public.admin_review_comments, public.comment_likes, public.user_review_likes to anon, authenticated;
