-- Privacy-first website analytics for the CineMood admin dashboard.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  visitor_hash text not null,
  session_id text,
  event_type text not null check (event_type in ('visit','movie_open','search','google_login')),
  movie_id text,
  path text,
  referrer_host text,
  created_at timestamptz not null default now()
);
create index if not exists idx_analytics_created on public.analytics_events(created_at desc);
create index if not exists idx_analytics_type_created on public.analytics_events(event_type, created_at desc);
create index if not exists idx_analytics_visitor on public.analytics_events(visitor_hash, created_at desc);
alter table public.analytics_events enable row level security;
-- No public policies: events are written/read only by the server service role.
revoke all on public.analytics_events from anon, authenticated;
